// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ofptoiarshquhrvhnssn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9mcHRvaWFyc2hxdWhydmhuc3NuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMDU4NjksImV4cCI6MjA3MDU4MTg2OX0.uI--d_hawmMxq_r5c5ZuMELhH75qgN7Kc-np6nk6U4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});